# This is a basic workflow to help you get started with Actions

name: Coverage

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.8]

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install numpy coverage
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          
      - name: Run coverage and Report
        run: |
          coverage run -m unittest discover -s tests
          PERCENT=$( coverage report -m | tail -1 | awk '{print $4}' | sed 's/%//g' )
          echo $PERCENT
          if (( $(echo "$PERCENT <= 50" | bc -l) )) ; then
            COLOR=red
          elif (( $(echo "$PERCENT > 80" | bc -l) )); then
            COLOR=green
          else
            COLOR=orange
          fi
          echo $COLOR
          
      - name: Create Awesome Badge
        uses: schneegans/dynamic-badges-action@v1.0.0
        with:
          auth: ${{ secrets.GIST_SECRET }}
          gistID: c8f263678e4e1f57994fa049a83a85ab
          filename: optional_imports_badge.json
          label: "🛡️ coverage"
          message: "80%"
          color: green
